ARG JDK_VERSION=17
ARG JDK_IMAGE=eclipse-temurin:${JDK_VERSION}-jdk


# =====
FROM $JDK_IMAGE AS eap-build

ARG EAP_VERSION
ARG MVN_OUTPUT

RUN apt update -y && \
    apt install -y wget unzip patch curl maven xmlstarlet && \
    mkdir /eap-build

WORKDIR /eap-build
COPY . ./
RUN ./build-eap.sh $EAP_VERSION && \ 
    unzip -q -d /opt dist/jboss-eap-*.zip && \ 
    mv /opt/jboss-eap-* /opt/jboss-eap


# =====
FROM $JDK_IMAGE

RUN groupadd -r jboss -g 1001 && \
    useradd -u 1001 -r -g jboss -m -d /opt/jboss-eap -s /sbin/nologin -c "JBoss user" jboss && \
    chmod 755 /opt/jboss-eap

COPY --from=eap-build --chown=jboss:0 /opt/jboss-eap /opt/jboss-eap

WORKDIR /opt/jboss-eap
USER jboss
ENV LAUNCH_JBOSS_IN_BACKGROUND=true

EXPOSE 8080
EXPOSE 9990

CMD ["bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
